# Generated by Django 5.0.7 on 2024-07-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url_video', models.URLField(max_length=500)),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
