# Generated by Django 5.0.7 on 2024-07-26 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Leveling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvideo',
            name='name_video',
            field=models.TextField(default='video'),
        ),
        migrations.AlterField(
            model_name='gvideo',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 19, 12, 45, 448111, tzinfo=datetime.timezone.utc)),
        ),
    ]
