# Generated by Django 5.0.7 on 2024-07-27 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Leveling', '0002_gvideo_name_video_alter_gvideo_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gvideo',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 10, 20, 25, 58163, tzinfo=datetime.timezone.utc)),
        ),
    ]
