# Generated by Django 5.0.7 on 2024-07-27 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Leveling', '0003_alter_gvideo_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gvideo',
            name='name_video',
        ),
        migrations.AddField(
            model_name='gvideo',
            name='comment_video',
            field=models.TextField(default='video'),
        ),
        migrations.AlterField(
            model_name='gvideo',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 10, 21, 10, 971231, tzinfo=datetime.timezone.utc)),
        ),
    ]
