# Generated by Django 5.0.7 on 2024-08-08 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Leveling', '0005_alter_gvideo_comment_video_alter_gvideo_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gvideo',
            name='comment_video',
            field=models.TextField(default='Comment was skipped', null=True),
        ),
        migrations.AlterField(
            model_name='gvideo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gvideo',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 8, 21, 53, 497892, tzinfo=datetime.timezone.utc)),
        ),
    ]
